# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf86e508713f07419c27831805af5817e0dc062f83c59621ebb0179814e6434299ac5bd435208e6d29d8ced220def2fabd7d681295a89897eb160b88b97594f1

test:
  secret_key_base: 51e8e51949ae54230ca2dfb92fe6b8982d500248aed5a92644d2fa3ca6a71e0e4a9046ce7f03b71e2fe43f4fdda0733ec53030f905e4ba4d1063c5d28c08132d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
